### ISSUE TITLE
[Feature] Support Piecewise Graph for VLM

### ISSUE THREAD

**Issue by yhyang201** [sgl-project/sglang#12838]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 2. Please use English, otherwise it will be closed.

### Motivation

[Feature] Support Piecewise Graph for VLM

It is recommended to first add support for the Qwen3VL and Qwen3VLMoE models.

**Comment by ping1jing2** [comment]
hope we can work on this task together

**Comment by yuan-luo** [comment]
> hope we can work on this task together

no problem. we can have discussion on slack. please ping me "Yuan Luo".

**Comment by ssshinigami** [comment]
Also we have implemented Piecewise Graph for Prefill https://github.com/sgl-project/sglang/pull/12287

**Comment by yuan-luo** [comment]
> Also we have implemented NPU Piecewise Graph for Prefill [#12287](https://github.com/sgl-project/sglang/pull/12287)

@ssshinigami Could you share some benchmark result for the Piecewise Cuda Graph improvement for Prefill and Decode?

**Comment by yuan-luo** [comment]
Currently VLM with piecewise cuda graph will encounter the following error.
Command to repro:
```
SGLANG_USE_CUDA_IPC_TRANSPORT=1 SGLANG_VLM_CACHE_SIZE_MB=0  python -m sglang.launch_server --model-path /home/admin/Qwen2.5-VL-72B-Instruct --host 0.0.0.0 --port 30000 --trust-remote-code --tp-size 8 --enable-cache-report --log-level info --max-running-requests 64 --mem-fraction-static 0.65 --chunked-prefill-size 8192 --attention-backend fa3 --chat-template qwen2-vl --mm-attention-backend fa3 --enable-metrics --enable-piecewise-cuda-graph --piecewise-cuda-graph-compiler eager
```

```
......
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
[2025-11-11 09:59:20 TP6] Scheduler hit an exception: Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2672, in run_scheduler_process
    scheduler = Scheduler(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 311, in __init__
    self.tp_worker = TpModelWorker(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 237, in __init__
    self._model_runner = ModelRunner(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 360, in __init__
    self.piecewise_cuda_graph_runner = PiecewiseCudaGraphRunner(self)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/piecewise_cuda_graph_runner.py", line 210, in __init__
    self.warmup_and_capture()
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/piecewise_cuda_graph_runner.py", line 267, in warmup_and_capture
    _ = self.model_runner.model.forward(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2_5_vl.py", line 580, in forward
    hidden_states = general_mm_embed_routine(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/mm_utils.py", line 701, in general_mm_embed_routine
    hidden_states = language_model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/compilation/compile.py", line 204, in trampoline
    _ensure_compiled(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/compilation/compile.py", line 195, in _ensure_compiled
    compiled_callable(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 745, in compile_wrapper
    raise e.with_traceback(None) from e.__cause__  # User compiler error
torch._dynamo.exc.Unsupported: Builtin `operator.*` comparison with constant `self` failed
  Explanation: Failed to compare GetAttrVariable(ConstantVariable(NoneType: None), ndim) with ConstantVariable(int: 1), because ConstantVariable(int: 1) is not a Python constant or its mutation check fails.


  Developer debug context: call_method GetAttrVariable(ConstantVariable(NoneType: None), ndim) __eq__ [ConstantVariable(int: 1)] {}


from user code:
   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 362, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 248, in forward
    hidden_states = self.self_attn(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 186, in forward
    q, k = self.rotary_emb(positions, q, k)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/layers/rotary_embedding.py", line 1461, in forward
    assert positions.ndim == 1 or positions.ndim == 2
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/polyfills/__init__.py", line 292, in cmp_eq
    result = a.__eq__(b)

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
```

I located the "assert positions.ndim == 1 or positions.ndim == 2" error's root cause. The reason is because during cuda graph capture, general_mm_embed_routine() enters the following branch.
```
    else:
        inputs_embeds = embed_tokens(input_ids)
```

I added an assertion “positions must be set for Qwen2/2.5-VL (MRoPE)” in def general_mm_embed_routine, which pinpoints the root cause:
```
    pos = kwargs.get("positions", getattr(forward_batch, "positions", None))
    assert pos is not None, "positions must be set for Qwen2/2.5-VL (MRoPE)" <<<<<<<<<<<
    hidden_states = language_model(
        input_ids=None,
        forward_batch=forward_batch,
        input_embeds=inputs_embeds,
        **kwargs,
    )
    return hidden_states
```

```
[2025-11-11 10:28:00 TP6] Scheduler hit an exception: Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2672, in run_scheduler_process
    scheduler = Scheduler(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 311, in __init__
    self.tp_worker = TpModelWorker(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 237, in __init__
    self._model_runner = ModelRunner(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 360, in __init__
    self.piecewise_cuda_graph_runner = PiecewiseCudaGraphRunner(self)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/piecewise_cuda_graph_runner.py", line 210, in __init__
    self.warmup_and_capture()
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/piecewise_cuda_graph_runner.py", line 267, in warmup_and_capture
    _ = self.model_runner.model.forward(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2_5_vl.py", line 580, in forward
    hidden_states = general_mm_embed_routine(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/mm_utils.py", line 733, in general_mm_embed_routine
    assert pos is not None, "positions must be set for Qwen2/2.5-VL (MRoPE)"
AssertionError: positions must be set for Qwen2/2.5-VL (MRoPE)
```
When entering language_model.forward(...), the positions required by Qwen2/2.5-VL’s rotary positional encoding (MRoPE) aren’t being passed in, so rotary_embedding.forward() receives None. Then, when TorchDynamo captures it and tries to evaluate positions.ndim == 1 or 2, it crashes (None.ndim).

I'm working on it. @mickqian @JustinTong0323

**Comment by yuan-luo** [comment]
Made some progress, currently CUDA graph capture passed. CUDA graph capture path: kwargs["positions"] is correctly passed through, and we also write back to forward_batch.positions; so the capture phase is OK.
But prefill mode still failed.
```
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
```
Piecewise warmup + torch.compile: Dynamo traces model.forward.
kwargs may be pruned/constant-folded, causing positions to “disappear” along the kwargs path.

The assertion in rotary_emb compares positions.ndim at Python level; during Dynamo’s symbolic phase it sees None which leads immediate error.
The logs above showing prefill becoming 1D also indicate that our “use the decode branch when L==1” fallback is being incorrectly triggered under warmup (prefill but L==1). This sometimes makes prefill 1D, which further increases the likelihood of such inputs being dropped/pruned along the compilation path.

Investigating.

```
Capturing batches (bs=1 avail_mem=31.23 GB):  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 11/12 [00:04<00:00,  3.99it/s][cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=False decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
[cap] flag=True decode=True has_mm=False got_pos=True shape=(3, 1)
Capturing batches (bs=1 avail_mem=31.23 GB): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:05<00:00,  2.31it/s]
[2025-11-11 14:24:55 TP0] Registering 1932 cuda graph addresses
[2025-11-11 14:24:56 TP4] Capture cuda graph end. Time elapsed: 6.43 s. mem usage=0.38 GB. avail mem=33.57 GB.
[2025-11-11 14:24:56 TP3] Capture cuda graph end. Time elapsed: 6.46 s. mem usage=0.38 GB. avail mem=33.57 GB.
[2025-11-11 14:24:56 TP7] Capture cuda graph end. Time elapsed: 6.42 s. mem usage=0.38 GB. avail mem=33.81 GB.
[2025-11-11 14:24:56 TP6] Capture cuda graph end. Time elapsed: 6.46 s. mem usage=0.38 GB. avail mem=33.57 GB.
[2025-11-11 14:24:56 TP1] Capture cuda graph end. Time elapsed: 6.44 s. mem usage=0.38 GB. avail mem=33.57 GB.
[2025-11-11 14:24:56 TP5] Capture cuda graph end. Time elapsed: 6.46 s. mem usage=0.38 GB. avail mem=33.57 GB.
[2025-11-11 14:24:56 TP2] Capture cuda graph end. Time elapsed: 6.44 s. mem usage=0.38 GB. avail mem=33.57 GB.
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
[2025-11-11 14:24:56 TP0] Capture cuda graph end. Time elapsed: 6.52 s. mem usage=0.38 GB. avail mem=31.21 GB.
[2025-11-11 14:24:56 TP0] Capture cuda graph num tokens [4, 8, 12, 16, 20, 24, 28, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 256, 288, 320, 352, 384, 416, 448, 480, 512, 640, 768, 896, 1024, 1152, 1280, 1408, 1536, 1664, 1792, 1920, 2048, 2176, 2304, 2432, 2560, 2688, 2816, 2944, 3072, 3200, 3328, 3456, 3584, 3712, 3840, 3968, 4096]
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
[cap] flag=False decode=False has_mm=False got_pos=True shape=(2,)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
/opt/conda/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py:1575: UserWarning: Dynamo detected a call to a `functools.lru_cache`-wrapped function. Dynamo ignores the cache wrapper and directly traces the wrapped function. Silent incorrectness is only a *potential* risk, not something we have observed. Enable TORCH_LOGS="+dynamo" for a DEBUG stack trace.
  torch._dynamo.utils.warn_once(msg)
[2025-11-11 14:24:56 TP4] Scheduler hit an exception: Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2672, in run_scheduler_process
    scheduler = Scheduler(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 311, in __init__
    self.tp_worker = TpModelWorker(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 237, in __init__
    self._model_runner = ModelRunner(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 360, in __init__
    self.piecewise_cuda_graph_runner = PiecewiseCudaGraphRunner(self)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/piecewise_cuda_graph_runner.py", line 210, in __init__
    self.warmup_and_capture()
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/piecewise_cuda_graph_runner.py", line 267, in warmup_and_capture
    _ = self.model_runner.model.forward(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2_5_vl.py", line 580, in forward
    hidden_states = general_mm_embed_routine(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/mm_utils.py", line 755, in general_mm_embed_routine
    hidden_states = language_model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/compilation/compile.py", line 204, in trampoline
    _ensure_compiled(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/compilation/compile.py", line 195, in _ensure_compiled
    compiled_callable(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 745, in compile_wrapper
    raise e.with_traceback(None) from e.__cause__  # User compiler error
torch._dynamo.exc.Unsupported: Builtin `operator.*` comparison with constant `self` failed
  Explanation: Failed to compare GetAttrVariable(ConstantVariable(NoneType: None), ndim) with ConstantVariable(int: 1), because ConstantVariable(int: 1) is not a Python constant or its mutation check fails.


  Developer debug context: call_method GetAttrVariable(ConstantVariable(NoneType: None), ndim) __eq__ [ConstantVariable(int: 1)] {}


```
