### ISSUE TITLE
[Bug] sglang doesn't stop the generation when the request is canceled

### ISSUE THREAD

**Issue by tchaton** [sgl-project/sglang#3520]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

I have been experimenting with sglang. Amazing work there !

I have found that sgland continues to generate even if the request has been canceled by the client.

It would be great if it wasn't the case. 

### Reproduction

Start the server, send a request, cancel it.

### Environment

I was using 2 * H200 to serve R1 600B

**Comment by jhinpan** [comment]
Thank you for your suggestion and kind words! We will try to introduce a cancellation token or flag within the client-server communication. When the client cancels the request, this token is triggered, signaling the generation routine to stop. This could potentially avoid wasting computational resources and ensures that only active requests consume server capacity.

If you want, you are also welcome to contribute and raise a PR about this enhancement!

**Comment by Chevolier** [comment]
I was wondering how was the development of this feature going? Is this available now?

**Comment by kratorado** [comment]
met the same problem

**Comment by tchaton** [comment]
Hey @merrymercy @jhinpan I wondered if this would be considered. This is making very dynamic inference with long context length quite challenging.

**Comment by miikatoi** [comment]
Possibly fixed in [#6184](https://github.com/sgl-project/sglang/pull/6184) or earlier.

If I clone the repo and run model server inside the dev container, cancellation works correctly. However, if I use the `lmsysorg/sglang:latest` Docker image to serve the model, cancellation does not seem to be effective yet.

**Comment by Mobious** [comment]
I posted this in #6280

Have you tested this with both streaming and non-streaming requests? I noticed in testing that cancelling requests with `stream=True` causes them to stop running immediately, while requests with `stream=False` seem to run to completion long after the client has terminated the connection.

I believe the cause for this is that FastAPI will raise a `asyncio.CancelledError` inside the StreamingResponse's streaming iterator when the client closes the connection. However, `StreamingResponse` isn't used when `stream=False`, so no `asyncio.CancelledError` is raised in this case.

For FastAPI server's I've implemented, I found this [middleware solution](https://github.com/fastapi/fastapi/discussions/11360) to be useful. Perhaps it could be added to SGL.

**Comment by RonanKMcGovern** [comment]
Any updates here, def useful for long requests

**Comment by finetunej** [comment]
This issue still exists. I've encountered it with non-streaming requests using PD disaggregation.

**Comment by b8zhong** [comment]
`/abort_request`

**Comment by finetunej** [comment]
That endpoint existing doesn't really help unless the router calls it when requests are cancelled.

**Comment by Mobious** [comment]
I agree with @finetunej. /abort_request is relatively useless for external clients using the API because:

- Requests with `stream=True` are already canceled after the client closes the connection.
- When `stream=False`, clients will not receive the request `id` that is needed to cancel the request until the request has already been fully completed.

EDIT:

I just realized that `/generate` allows you to provide your own `rid` which can then be used with `/abort_request` to cancel the request. So not as bad as I thought. Though this still requires clients to implement this behavior themselves, and even if they do, requests still can't be cancelled in certain cases such as a client crash.

It would still be nice if the SGL server would auto-cancel requests when it detects the connection is no longer open.
