### ISSUE TITLE
[Bug] The Prometheus metric `avg_request_queue_latency` is not being collected

### ISSUE THREAD

**Issue by jorgeantonio21** [sgl-project/sglang#6357]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

I have integrate Sglang metrics with Grafana dashboards, and the metric `avg_request_queue_latency` is not currently available, while all the other metrics are being collected. 

The `avg_request_queue_latency` is of importance for understanding the behavior of the system in high load situations.

### Reproduction

You can query Prometheus metrics at http://localhost:3000/metrics

### Environment

I have deployed using docker compose:

```yaml
sglang:
    container_name: sglang
    profiles: [chat_completions_sglang]
    image: lmsysorg/sglang:latest
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    restart: always
    network_mode: host # required by RDMA
    privileged: true # required by RDMA
    environment:
      HF_TOKEN: ${HF_TOKEN}
    entrypoint: python3 -m sglang.launch_server
    command:
      --model-path ${SGLANG_MODEL_PATH} --tp 8 --enable-dp-attention --dp 8 --trust-remote-code --max-running-requests 128 --enable-metrics
      --host 0.0.0.0
      --port 3000
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
```

**Comment by b8zhong** [comment]
It may simply be resolved by

```python
def log_stats(self, stats: SchedulerStats) -> None:
    self._log_gauge(self.num_running_reqs, stats.num_running_reqs)
    self._log_gauge(self.num_used_tokens, stats.num_used_tokens)
    self._log_gauge(self.token_usage, stats.token_usage)
    self._log_gauge(self.gen_throughput, stats.gen_throughput)
    self._log_gauge(self.num_queue_reqs, stats.num_queue_reqs)
    self._log_gauge(self.num_grammar_queue_reqs, stats.num_grammar_queue_reqs)
    self._log_gauge(self.cache_hit_rate, stats.cache_hit_rate)
    self._log_gauge(self.spec_accept_length, stats.spec_accept_length)
    # Missing: self._log_gauge(self.avg_request_queue_latency, stats.avg_request_queue_latency)
    
    # Disaggregation metrics
    # ... more metrics
```

Can you give this a try?

**Comment by PrinsYin** [comment]
Hi! I am a first-time contributor and would like to try on this issue. Can I be assigned to this one if possible?

**Comment by jorgeantonio21** [comment]
@b8zhong absolutely, thanks for the reference. I opened this PR, in the meantime:

https://github.com/sgl-project/sglang/pull/6574

**Comment by ianliuy** [comment]
I've confirmed that vg_request_queue_latency is still missing on HEAD. The metric was previously fixed in #8627 but was subsequently removed in #11123 during a broader metrics cleanup.

The existing sglang:queue_time_seconds histogram captures per-request queue time at dequeue (historical distribution), but it cannot answer **\"how long ARE requests currently waiting?\"**  which is what Grafana real-time alerting and autoscaling triggers need.

I'm working on a fix that re-introduces this as a Gauge, computed from the existing \wait_queue_entry_time\ timestamps on queued requests. PR incoming.

Related: #6574, #20159

**Comment by ianliuy** [comment]
Opened PR: https://github.com/sgl-project/sglang/pull/22613

cc @hnyls2002

**Comment by aryansharma2k2** [comment]
Hi, I'd like to pick this up if it's still open. I found [#22613](https://github.com/sgl-project/sglang/pull/22613) from @ianliuy . It's had no activity since April.

@ianliuy, are you still working on this? If not, I'd like to reimplement it against current main, with the feedback from that PR (shared helper for the wait-time calc instead of duplicating it across prefill/decode).

**Comment by Guts1005** [comment]
FYI @aryansharma2k2, I opened #38228 yesterday implementing this with the shared wait-time helper against current main. Currently waiting on maintainer review.
